/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialLinks".
 */
export type SocialLinks =
  | {
      socialNetwork: 'Facebook' | 'Instagram' | 'X' | 'LinkedIn' | 'YouTube';
      url: string;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    sitewideContent: SitewideContent;
  };
  globalsSelect: {
    sitewideContent: SitewideContentSelect<false> | SitewideContentSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  url?: string | null;
  template?: ('page-builder' | 'base-page' | 'contact-us' | 'what-we-do-subpage') | null;
  /**
   * Hex color code for the page accent color
   */
  accentColor?: string | null;
  layout?:
    | (
        | Brands
        | CardsCarousel
        | CreativeTestimonial
        | FloatingNumbers
        | FloatingTeam
        | FloatingTeam2
        | Hero2
        | HeroCarousel
        | HeroHomepage
        | HeroWithImage
        | OtherPillars
        | OurPeople
        | OurPillars
        | OurValues
        | Reviews
        | StatementText
        | Stories
        | Testimonial
        | TextBlock
        | TextReveal
        | TextWithImage
        | TitleBlock
        | TitleWithImage
        | VideoScrub
      )[]
    | null;
  basePageTemplate?: BasePageTemplate;
  contactUsTemplate?: ContactUsTemplate;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    noIndexing?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Brands".
 */
export interface Brands {
  blockName?: string | null;
  title: string;
  copy?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyHTML?: string | null;
  images: (string | Media)[];
  textWithImage: {
    blockName?: string | null;
    image: string | Media;
    aspectRatio?: ('square' | 'portrait') | null;
    copy?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    copyHTML?: string | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
    };
  };
  id?: string | null;
  blockType: 'brands';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsCarousel".
 */
export interface CardsCarousel {
  blockName?: string | null;
  title: string;
  items: {
    title: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockType: 'cards-carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreativeTestimonial".
 */
export interface CreativeTestimonial {
  blockName?: string | null;
  subTitle?: string | null;
  title: string;
  name: string;
  role: string;
  slide1: {
    text: string;
  };
  slide2: {
    image: string | Media;
    text1: string;
    text2: string;
  };
  id?: string | null;
  blockType: 'creative-testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FloatingNumbers".
 */
export interface FloatingNumbers {
  blockName?: string | null;
  subTitle?: string | null;
  title: string;
  items?:
    | {
        number: number;
        title: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'floating-numbers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FloatingTeam".
 */
export interface FloatingTeam {
  blockName?: string | null;
  subTitle: string;
  title: string;
  items?:
    | {
        image: string | Media;
        bgColor?: string | null;
        name: string;
        post?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'floating-team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FloatingTeam2".
 */
export interface FloatingTeam2 {
  blockName?: string | null;
  title: string;
  items?:
    | {
        label: string;
        /**
         * Team member's name
         */
        name: string;
        /**
         * Description or bio of the team member
         */
        copy?: string | null;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'floating-team2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero2".
 */
export interface Hero2 {
  blockName?: string | null;
  title: string;
  copy?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyHTML?: string | null;
  image: string | Media;
  id?: string | null;
  blockType: 'hero2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCarousel".
 */
export interface HeroCarousel {
  blockName?: string | null;
  title: string;
  copy?: string | null;
  images: (string | Media)[];
  id?: string | null;
  blockType: 'hero-carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomepage".
 */
export interface HeroHomepage {
  blockName?: string | null;
  /**
   * Use the | symbol to indicate where a video block should be inserted
   */
  title: string;
  image: string | Media;
  vimeoVideoId?: string | null;
  id?: string | null;
  blockType: 'hero-homepage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroWithImage".
 */
export interface HeroWithImage {
  blockName?: string | null;
  title: string;
  image: string | Media;
  id?: string | null;
  blockType: 'hero-with-image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OtherPillars".
 */
export interface OtherPillars {
  blockName?: string | null;
  title: string;
  prev?: {
    /**
     * Enter a hex color code (e.g. #FFFFFF)
     */
    bgColor?: string | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
    };
  };
  next?: {
    /**
     * Enter a hex color code (e.g. #FFFFFF)
     */
    bgColor?: string | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
    };
  };
  id?: string | null;
  blockType: 'other-pillars';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurPeople".
 */
export interface OurPeople {
  blockName?: string | null;
  title: string;
  copy?: string | null;
  people?:
    | {
        name: string;
        role?: string | null;
        /**
         * Enter a hex color code (e.g. #FFFFFF)
         */
        avatarBgColor?: string | null;
        avatar?: (string | null) | Media;
        avatarFunny?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'our-people';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurPillars".
 */
export interface OurPillars {
  blockName?: string | null;
  title: string;
  items?:
    | {
        /**
         * Recommended size: 794x1050
         */
        image: string | Media;
        title: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'our-pillars';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurValues".
 */
export interface OurValues {
  blockName?: string | null;
  title: string;
  items?:
    | {
        label: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'our-values';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Reviews".
 */
export interface Reviews {
  blockName?: string | null;
  subTitle?: string | null;
  title: string;
  items?:
    | {
        image: string | Media;
        title: string;
        role?: string | null;
        quote?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        quoteHTML?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'reviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementText".
 */
export interface StatementText {
  blockName?: string | null;
  subTitle?: string | null;
  /**
   * Use the | symbol to indicate where a image block should be inserted
   */
  title: string;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  id?: string | null;
  blockType: 'statement-text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Stories".
 */
export interface Stories {
  blockName?: string | null;
  subTitle?: string | null;
  title: string;
  items?:
    | {
        bgColor?: ('purple' | 'pink' | 'teal') | null;
        title: string;
        tags?: string[] | null;
        image: string | Media;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'stories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonial".
 */
export interface Testimonial {
  blockName?: string | null;
  image: string | Media;
  quote: string;
  name?: string | null;
  role?: string | null;
  id?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  blockName?: string | null;
  title?: string | null;
  titleStyle?: ('default' | 'small') | null;
  copy?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyHTML?: string | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  id?: string | null;
  blockType: 'text-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextReveal".
 */
export interface TextReveal {
  blockName?: string | null;
  title: string;
  copy?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyHTML?: string | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  id?: string | null;
  blockType: 'text-reveal';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithImage".
 */
export interface TextWithImage {
  blockName?: string | null;
  image: string | Media;
  aspectRatio?: ('square' | 'portrait') | null;
  copy?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyHTML?: string | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  id?: string | null;
  blockType: 'text-with-image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleBlock".
 */
export interface TitleBlock {
  blockName?: string | null;
  titleLine1: string;
  imageLine1: string | Media;
  image1Line2: string | Media;
  image2Line2: string | Media;
  titleLine2: string;
  video?: {
    vimeoVideoId?: string | null;
    marqueeText?: string | null;
  };
  id?: string | null;
  blockType: 'title-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithImage".
 */
export interface TitleWithImage {
  blockName?: string | null;
  subTitle?: string | null;
  title: string;
  image?: (string | null) | Media;
  enableButtons?: boolean | null;
  buttons?:
    | {
        isActive?: boolean | null;
        /**
         * Enter a hex color code (e.g. #FFFFFF)
         */
        color?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockType: 'title-with-image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoScrub".
 */
export interface VideoScrub {
  blockName?: string | null;
  id?: string | null;
  blockType: 'video-scrub';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BasePageTemplate".
 */
export interface BasePageTemplate {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_html?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactUsTemplate".
 */
export interface ContactUsTemplate {
  blockName?: string | null;
  title: string;
  copy: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  copyHTML?: string | null;
  contacts?:
    | {
        label: string;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  people?:
    | {
        image: string | Media;
        activeImage?: (string | null) | Media;
        name: string;
        copy: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        copyHTML?: string | null;
        contacts?:
          | {
              label: string;
              value: string;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url?: T;
  template?: T;
  accentColor?: T;
  layout?:
    | T
    | {
        brands?: T | BrandsSelect<T>;
        'cards-carousel'?: T | CardsCarouselSelect<T>;
        'creative-testimonial'?: T | CreativeTestimonialSelect<T>;
        'floating-numbers'?: T | FloatingNumbersSelect<T>;
        'floating-team'?: T | FloatingTeamSelect<T>;
        'floating-team2'?: T | FloatingTeam2Select<T>;
        hero2?: T | Hero2Select<T>;
        'hero-carousel'?: T | HeroCarouselSelect<T>;
        'hero-homepage'?: T | HeroHomepageSelect<T>;
        'hero-with-image'?: T | HeroWithImageSelect<T>;
        'other-pillars'?: T | OtherPillarsSelect<T>;
        'our-people'?: T | OurPeopleSelect<T>;
        'our-pillars'?: T | OurPillarsSelect<T>;
        'our-values'?: T | OurValuesSelect<T>;
        reviews?: T | ReviewsSelect<T>;
        'statement-text'?: T | StatementTextSelect<T>;
        stories?: T | StoriesSelect<T>;
        testimonial?: T | TestimonialSelect<T>;
        'text-block'?: T | TextBlockSelect<T>;
        'text-reveal'?: T | TextRevealSelect<T>;
        'text-with-image'?: T | TextWithImageSelect<T>;
        'title-block'?: T | TitleBlockSelect<T>;
        'title-with-image'?: T | TitleWithImageSelect<T>;
        'video-scrub'?: T | VideoScrubSelect<T>;
      };
  basePageTemplate?: T | BasePageTemplateSelect<T>;
  contactUsTemplate?: T | ContactUsTemplateSelect<T>;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndexing?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  copy?: T;
  copyHTML?: T;
  images?: T;
  textWithImage?:
    | T
    | {
        blockName?: T;
        image?: T;
        aspectRatio?: T;
        copy?: T;
        copyHTML?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsCarousel_select".
 */
export interface CardsCarouselSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  items?:
    | T
    | {
        title?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreativeTestimonial_select".
 */
export interface CreativeTestimonialSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  name?: T;
  role?: T;
  slide1?:
    | T
    | {
        text?: T;
      };
  slide2?:
    | T
    | {
        image?: T;
        text1?: T;
        text2?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FloatingNumbers_select".
 */
export interface FloatingNumbersSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FloatingTeam_select".
 */
export interface FloatingTeamSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  items?:
    | T
    | {
        image?: T;
        bgColor?: T;
        name?: T;
        post?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FloatingTeam2_select".
 */
export interface FloatingTeam2Select<T extends boolean = true> {
  blockName?: T;
  title?: T;
  items?:
    | T
    | {
        label?: T;
        name?: T;
        copy?: T;
        image?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero2_select".
 */
export interface Hero2Select<T extends boolean = true> {
  blockName?: T;
  title?: T;
  copy?: T;
  copyHTML?: T;
  image?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCarousel_select".
 */
export interface HeroCarouselSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  copy?: T;
  images?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomepage_select".
 */
export interface HeroHomepageSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  image?: T;
  vimeoVideoId?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroWithImage_select".
 */
export interface HeroWithImageSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  image?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OtherPillars_select".
 */
export interface OtherPillarsSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  prev?:
    | T
    | {
        bgColor?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
      };
  next?:
    | T
    | {
        bgColor?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurPeople_select".
 */
export interface OurPeopleSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  copy?: T;
  people?:
    | T
    | {
        name?: T;
        role?: T;
        avatarBgColor?: T;
        avatar?: T;
        avatarFunny?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurPillars_select".
 */
export interface OurPillarsSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  items?:
    | T
    | {
        image?: T;
        title?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurValues_select".
 */
export interface OurValuesSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  items?:
    | T
    | {
        label?: T;
        copy?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  items?:
    | T
    | {
        image?: T;
        title?: T;
        role?: T;
        quote?: T;
        quoteHTML?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementText_select".
 */
export interface StatementTextSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  items?:
    | T
    | {
        bgColor?: T;
        title?: T;
        tags?: T;
        image?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonial_select".
 */
export interface TestimonialSelect<T extends boolean = true> {
  blockName?: T;
  image?: T;
  quote?: T;
  name?: T;
  role?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  titleStyle?: T;
  copy?: T;
  copyHTML?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextReveal_select".
 */
export interface TextRevealSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  copy?: T;
  copyHTML?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithImage_select".
 */
export interface TextWithImageSelect<T extends boolean = true> {
  blockName?: T;
  image?: T;
  aspectRatio?: T;
  copy?: T;
  copyHTML?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleBlock_select".
 */
export interface TitleBlockSelect<T extends boolean = true> {
  blockName?: T;
  titleLine1?: T;
  imageLine1?: T;
  image1Line2?: T;
  image2Line2?: T;
  titleLine2?: T;
  video?:
    | T
    | {
        vimeoVideoId?: T;
        marqueeText?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithImage_select".
 */
export interface TitleWithImageSelect<T extends boolean = true> {
  blockName?: T;
  subTitle?: T;
  title?: T;
  image?: T;
  enableButtons?: T;
  buttons?:
    | T
    | {
        isActive?: T;
        color?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoScrub_select".
 */
export interface VideoScrubSelect<T extends boolean = true> {
  blockName?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BasePageTemplate_select".
 */
export interface BasePageTemplateSelect<T extends boolean = true> {
  content?: T;
  content_html?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactUsTemplate_select".
 */
export interface ContactUsTemplateSelect<T extends boolean = true> {
  blockName?: T;
  title?: T;
  copy?: T;
  copyHTML?: T;
  contacts?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  people?:
    | T
    | {
        image?: T;
        activeImage?: T;
        name?: T;
        copy?: T;
        copyHTML?: T;
        contacts?:
          | T
          | {
              label?: T;
              value?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitewideContent".
 */
export interface SitewideContent {
  id: string;
  header: PrimaryHeader;
  socialLinks?: SocialLinks;
  footer: PrimaryFooter;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrimaryHeader".
 */
export interface PrimaryHeader {
  navigation: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
    };
    id?: string | null;
  }[];
  sideNavigation?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  copy1?: string | null;
  copy2?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrimaryFooter".
 */
export interface PrimaryFooter {
  navigation: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
    };
    id?: string | null;
  }[];
  contacts: {
    label: string;
    items?:
      | {
          label: string;
          value?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          valueHTML?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  copyright?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyrightHTML?: string | null;
  devCopyright?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  devCopyrightHTML?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitewideContent_select".
 */
export interface SitewideContentSelect<T extends boolean = true> {
  header?: T | PrimaryHeaderSelect<T>;
  socialLinks?: T | SocialLinksSelect<T>;
  footer?: T | PrimaryFooterSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrimaryHeader_select".
 */
export interface PrimaryHeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  sideNavigation?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  copy1?: T;
  copy2?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialLinks_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  socialNetwork?: T;
  url?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrimaryFooter_select".
 */
export interface PrimaryFooterSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  contacts?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              label?: T;
              value?: T;
              valueHTML?: T;
              id?: T;
            };
      };
  copyright?: T;
  copyrightHTML?: T;
  devCopyright?: T;
  devCopyrightHTML?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}